# Note: This crate must be built using do.sh

[package]
name = "wormhole-bridge"
version = "0.1.0"
description = "Solana Program Library Token Swap"
authors = ["Certus One Team <info@certus.one>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
skip-no-mangle = ["solana-sdk/skip-no-mangle"]

[dependencies]
num-derive = "0.2"
num-traits = "0.2"
remove_dir_all = "=0.5.0"
solana-sdk = { version = "=1.2.13", default-features = false, features = ["program"] }
spl-token = { git = "https://github.com/solana-labs/solana-program-library" }
thiserror = "1.0"
libsecp256k1 = "0.3.5"
sha3 = "0.9.1"
hex = "0.4.2"
arrayref = "0.3.6"
byteorder = "1.3.4"

[dev-dependencies]
rand = { version = "0.7.0" }

[build-dependencies]
cbindgen = "=0.14.2"

[lib]
name = "spl_token_swap"
crate-type = ["cdylib", "lib"]
